---
- name: Get the current directory
  ansible.builtin.command:
    cmd: pwd
  register: pwd_output

- name: test
  ansible.builtin.debug:
    msg:
      - "{{ pwd_output.stdout | dirname }}/Homeflix"

- name: Change to the Homeflix directory
  ansible.builtin.command:
    cmd: "echo 'changed directory'"
  args:
    chdir: "{{ pwd_output.stdout | dirname }}/Homeflix" 

- name: Change the folder permissions of the Movie/Shows folder
  become: true
  become_user: root
  ansible.builtin.command:
    cmd: sudo chmod 777 radarr/movies