name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 
      
      - name: Test
        run: echo "Hello World"

      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install -y git ansible

      - name: Clone Repository
        run: |
          git clone https://github.com/Salzstange-app/Homeflix.git

      - name: Start Bash Script
        run: |
          bash .sh
  tests:
    runs-on: ubuntu-latest  
    needs: build 

    steps:
      - name: Wait for Services
        run: |
          sleep 20 # Adjust as necessary for your services to start

      - name: Check Sonarr
        run: |
          curl --fail http://localhost:8989/api/v1/system/status || echo "Sonarr is not running"

      - name: Check Radarr
        run: |
          curl --fail http://localhost:7878/api/v1/system/status || echo "Radarr is not running"

      - name: Check Sabnzbd
        run: |
          curl --fail http://localhost:8080/api/v2/sabnzbd/pause || echo "Sabnzbd is not running"

      - name: Check Jellyfin
        run: |
          curl --fail http://localhost:8096/Users || echo "Jellyfin is not running"
